version: 0.2

phases:
  install:
    commands:
      - echo update npm...
      - echo node -v
      - node -v
      - echo npm -v
      - npm -v
      - echo install yarn...
      - npm install -g yarn
      - echo yarn -v
      - yarn -v
  pre_build:
    commands:
      - echo Installing server dependencies...
      - yarn install
      - echo Installing client dependences
      - cd client
      - yarn install
      - cd ..
  build:
    commands:
      - echo Build started on `date`
      - yarn tsc
      - yarn build-client
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - dist/**/*
